"$schema" = "https://starship.rs/config-schema.json"

format = "$directory$git_branch$git_status$fill$shell$character"
right_format = "$time"
continuation_prompt = "[∙](bright-black) "
scan_timeout = 30
command_timeout = 5000
add_newline = true

[character]
format = "$symbol "
success_symbol = "[❯](bold cyan)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_visual_symbol = "[❮](bold yellow)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_replace_one_symbol = "[❮](bold purple)"

[directory]
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 0
format = "[$path]($style) "
style = "cyan bold"
home_symbol = "~"

[git_branch]
format = "on [$symbol$branch]($style) "
symbol = " "
style = "bold purple"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "red bold"
stashed = "\\$"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
conflicted = "="
deleted = "✘"
renamed = "»"
modified = "!"
staged = "+"
untracked = "?"

[shell]
format = "[$indicator]($style) "
fish_indicator = ""
bash_indicator = ""
zsh_indicator = ""
style = "white bold"
disabled = false

[time]
format = "[\\[$time\\]]($style) "
style = "bold green"
use_12hr = false
disabled = false
utc_time_offset = "local"

[fill]
style = "bold black"
symbol = "."
